# Generated by Django 4.1.5 on 2023-02-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscribers_category',
        ),
    ]
